config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  get '/posts', to: 'posts#index', as: 'posts'
  get '/post/:id', to: 'posts#show', as: 'post'

  get '/categories', to: 'categories#index', as: 'categories'
  get '/category/:name', to: 'categories#show', as: 'category'

  get '/u/posts', to: 'users_categories#index', as: 'users_posts'
  get '/u/categories', to: 'users_categories#categories', as: 'users_categories'
  post '/u/subscribe_user_category', to: 'users_categories#subscribe_category', as: 'subscribe_user_category'
  post '/u/unsubscribe_user_category', to: 'users_categories#unsubscribe_category', as: 'unsubscribe_user_category'

  use_doorkeeper
  namespace :api do
    get '/posts', to: 'posts#index', as: 'posts'
    get '/post/:id', to: 'posts#show', as: 'post'

    get '/categories', to: 'categories#index', as: 'categories'
    get '/category/:name', to: 'categories#show', as: 'category'

    get '/u/posts', to: 'users_categories#index', as: 'users_posts'
    get '/user', to: 'users_categories#me', as: 'users_details'
    get '/u/categories', to: 'users_categories#categories', as: 'users_categories'
    post '/u/add_user_category', to: 'users_categories#subscribe_category', as: 'add_user_category'
    post '/u/remove_user_category', to: 'users_categories#unsubscribe_category', as: 'remove_user_category'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/users_categories_controller.rb
class Api::UsersCategoriesController < Api::UsersController

  def me
    puts "........me......."
    render(json: doorkeeper_token)
  end

  def index
    user_categories=UserCategory
                    .select('categories.name')
                    .joins(:category)
                    .where('users_categories.user_id' => current_user.id)


    posts=Neo4j::ActiveBase.current_session.query("
            MATCH (n:Article)-[:BELONG_TO]->(c:Category)
            WHERE ANY
              (x IN #{user_categories.collect{|x| x.name}} WHERE x =~ c.name)
            RETURN n")
            .to_a
            .collect{|x| x.n.properties }
    render(json: {posts: posts})
  end


  def categories
    @user_categories=UserCategory
                    .select('categories.name')
                    .joins(:category)
                    .where('users_categories.user_id' => current_user.id)
    @category=Category.new
  end

  def add_user_category
    @category=Category.find_by_name(user_category_params[:name]) || Category.create(user_category_params[:name])
    @user_category =UserCategory.create(category_id: @category.id, user_id: current_user.id)
  end

  def remove_user_category
    @category = Category.find_by_name(user_category_params[:name])
    @user_category =UserCategory.where(category_id: @category.id, user_id: current_user.id)
    UserCategory.destroy(@user_category.ids)
  end

  def subscribe_category
    add_user_category
    redirect_to users_categories_path
  end

  def unsubscribe_category
    remove_user_category
    redirect_to users_categories_path
  end

  private
   def user_category_params
     params.require(:category).permit(:name)
   end

end

app/controllers/users_categories_controller.rb
class UsersCategoriesController < UsersController
  def index
    @user_categories=UserCategory
                    .select('categories.name')
                    .joins(:category)
                    .where('users_categories.user_id' => current_user.id)

    @all_posts=Neo4j::ActiveBase.current_session.query("
            MATCH (n:Article)-[:BELONG_TO]->(c:Category)
            WHERE ANY
              (x IN #{@user_categories.collect{|x| x.name}} WHERE x =~ c.name)
            RETURN n")
            .to_a

    @posts=@all_posts
            .paginate(:page => params[:page], :per_page => 5)

    if params[:page]
      @page=params[:page].to_i
    else
      @page=1
    end
    @total_pages = ( @all_posts.length%5 == 0 ) ? @all_posts.length/5 : @all_posts.length/5+1

    @category=Category.new

  end


  def categories
    @user_categories=UserCategory
                    .select('categories.name')
                    .joins(:category)
                    .where('users_categories.user_id' => current_user.id)
    @category=Category.new
  end

  def subscribe_category
    category=Category.find_by_name(user_category_params[:name]) || Category.create(name: user_category_params[:name])
    user_category =UserCategory.create(category_id: category.id, user_id: current_user.id)
    redirect_back(fallback_location: root_path)
  end

  def unsubscribe_category
    category = Category.find_by_name(user_category_params[:name])
    user_category =UserCategory.where(category_id: category.id, user_id: current_user.id)
    UserCategory.destroy(user_category.ids)
    redirect_back(fallback_location: root_path)
  end

  private
   def user_category_params
     params.require(:category).permit(:name)
   end

end

app/views/users_categories/categories.html.erb
<%= render "components/navbar" %>
<%= render "components/search_bar" %>
<div class="container py-5 w-50">
  <h4> Categories</h4>
  <%= form_for @category, url: subscribe_user_category_path, class:'form-group'  do |form| %>
    <div class="input-group">
      <%= form.text_field :name, class:'form-control', placeholder: "Add Category"%>
      <span class="input-group-btn">
        <%= form.submit "Add", class:'btn btn-lg btn-success' %>
      </span>
    </div>
  <% end %>

  <h4 class="pt-5">Subcribed Categories</h4>
  <div class="container">
      <% @user_categories.each do |category| %>
        <div class="row py-4 ">
          <div class="col-md-6 ">
            <h2 class=""><%= link_to category.name, category_path(category.name) %></h2>

          </div>
          <div class="col-md-6 text-right">
            <%= form_for @category, url: unsubscribe_user_category_path, class: "form-group d-inline"  do |form| %>
                <%= form.text_field :name, value: category.name, type: "hidden" %>
                <%= form.submit "remove", class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
        <hr />
      <% end %>
  </div>
</div>

app/views/users_categories/index.html.erb
<%= render "components/navbar" %>
<%= render "components/search_bar" %>
<div class="container py-3 ">
  <div class="my-4">
    <% @posts.each do |post| %>
      <div class="my-5 mb-5">
        <%= link_to post_path(post.n.id) do%>
          <h2 class="text-dark"><%=  truncate(post.n.properties[:title], :length => 100)%></h2>
          <p class="list-group-item-text text-secondary pb-3"><%= truncate(post.n.properties[:content], :length => 250) %></p>
        <% end %>
        <hr />
      </div>
    <% end %>
  </div>

  <nav aria-label="Page navigation">
    <ul class="pagination">
      <li class="page-item">
        <%= link_to (@page>1) ? users_posts_path(page: "#{@page-1}") : "#", class: "page-link" do%>
          <b aria-label="Next">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Next</span>
          </b>
        <%end%>
      </li>
      <% for i in 1..@total_pages do %>
        <li class="page-item"><%= link_to "#{i}", users_posts_path(page: "#{i}"), class: "page-link" %></li>
      <%end%>

      <li class="page-item">
        <%= link_to (@page<@total_pages) ? users_posts_path(page: "#{@page+1}") : "#", class: "page-link" do%>
          <b aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </b>
        <%end%>
      </li>
    </ul>
  </nav>

</div>